### PR TITLE
Node with typings

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by michielbdejong** [comment]
This produces the content of https://github.com/cs3org/node-cs3apis/pull/10

**Review by labkode — APPROVED** [review]

**Comment by michielbdejong** [comment]
Ah, sorry for breaking the build!
I tested it locally and this error didn't happen - but apparently something was still wrong.
Thanks for reverting, @labkode!
I know that issue, it's why I had `run(exec.Command("ln", "-s", "third_party/google"))` but I thought it worked without it as well.

I'll prepare a new PR.

**Comment by michielbdejong** [comment]
Reproduced the problem using the instructions which this PR adds to the readme (but with `-build-node` instead of `-build-js`:
```sh
root@0ef91683dc6b:~/cs3apis# /root/cs3apis-build/cs3apis-build -build-node
Building Node.js ...
build [git clone --quiet https://github.com/cs3org/node-cs3apis]

. [git rev-parse --abbrev-ref HEAD]

build/node-cs3apis [git rev-parse --abbrev-ref HEAD]

Proto branch: main
Build branch: main
google/protobuf/field_mask.proto: File not found.
```

**Comment by michielbdejong** [comment]
And more directly:
```sh
root@0ef91683dc6b:~/cs3apis# /usr/lib/node_modules/protoc-gen-grpc/bin/protoc --plugin=protoc-gen-ts=/usr/lib/node_modules/protoc-gen-grpc/bin/protoc-gen-ts-plugin --ts_out=grpc_js:./build/node-cs3apis cs3/gateway/v1beta1/gateway_api.proto cs3/gateway/v1beta1/resources.proto cs3/permissions/v1beta1/permissions_api.proto cs3/permissions/v1beta1/resources.proto cs3/preferences/v1beta1/preferences_api.proto cs3/rpc/v1beta1/code.proto cs3/rpc/v1beta1/status.proto cs3/tx/v1beta1/resources.proto cs3/tx/v1beta1/tx_api.proto cs3/types/v1beta1/types.proto cs3/admin/group/v1beta1/group_api.proto cs3/admin/user/v1beta1/user_api.proto cs3/app/provider/v1beta1/provider_api.proto cs3/app/provider/v1beta1/resources.proto cs3/app/registry/v1beta1/registry_api.proto cs3/app/registry/v1beta1/resources.proto cs3/auth/applications/v1beta1/applications_api.proto cs3/auth/applications/v1beta1/resources.proto cs3/auth/provider/v1beta1/provider_api.proto cs3/auth/provider/v1beta1/resources.proto cs3/auth/registry/v1beta1/registry_api.proto cs3/auth/registry/v1beta1/resources.proto cs3/identity/group/v1beta1/group_api.proto cs3/identity/group/v1beta1/resources.proto cs3/identity/user/v1beta1/resources.proto cs3/identity/user/v1beta1/user_api.proto cs3/ocm/core/v1beta1/ocm_core_api.proto cs3/ocm/core/v1beta1/resources.proto cs3/ocm/invite/v1beta1/invite_api.proto cs3/ocm/invite/v1beta1/resources.proto cs3/ocm/provider/v1beta1/provider_api.proto cs3/ocm/provider/v1beta1/resources.proto cs3/sharing/collaboration/v1beta1/collaboration_api.proto cs3/sharing/collaboration/v1beta1/resources.proto cs3/sharing/link/v1beta1/link_api.proto cs3/sharing/link/v1beta1/resources.proto cs3/sharing/ocm/v1beta1/ocm_api.proto cs3/sharing/ocm/v1beta1/resources.proto cs3/storage/provider/v1beta1/provider_api.proto cs3/storage/provider/v1beta1/resources.proto cs3/storage/registry/v1beta1/registry_api.proto cs3/storage/registry/v1beta1/resources.proto
google/protobuf/field_mask.proto: File not found.
```

**Comment by michielbdejong** [comment]
Ah, this works:
```
/usr/lib/node_modules/protoc-gen-grpc/bin/protoc --plugin=protoc-gen-ts=/usr/lib/node_modules/protoc-gen-grpc/bin/protoc-gen-ts-plugin --ts_out=grpc_js:./build/node-cs3apis cs3/gateway/v1beta1/gateway_api.proto cs3/gateway/v1beta1/resources.proto cs3/permissions/v1beta1/permissions_api.proto cs3/permissions/v1beta1/resources.proto cs3/preferences/v1beta1/preferences_api.proto cs3/rpc/v1beta1/code.proto cs3/rpc/v1beta1/status.proto cs3/tx/v1beta1/resources.proto cs3/tx/v1beta1/tx_api.proto cs3/types/v1beta1/types.proto cs3/admin/group/v1beta1/group_api.proto cs3/admin/user/v1beta1/user_api.proto cs3/app/provider/v1beta1/provider_api.proto cs3/app/provider/v1beta1/resources.proto cs3/app/registry/v1beta1/registry_api.proto cs3/app/registry/v1beta1/resources.proto cs3/auth/applications/v1beta1/applications_api.proto cs3/auth/applications/v1beta1/resources.proto cs3/auth/provider/v1beta1/provider_api.proto cs3/auth/provider/v1beta1/resources.proto cs3/auth/registry/v1beta1/registry_api.proto cs3/auth/registry/v1beta1/resources.proto cs3/identity/group/v1beta1/group_api.proto cs3/identity/group/v1beta1/resources.proto cs3/identity/user/v1beta1/resources.proto cs3/identity/user/v1beta1/user_api.proto cs3/ocm/core/v1beta1/ocm_core_api.proto cs3/ocm/core/v1beta1/resources.proto cs3/ocm/invite/v1beta1/invite_api.proto cs3/ocm/invite/v1beta1/resources.proto cs3/ocm/provider/v1beta1/provider_api.proto cs3/ocm/provider/v1beta1/resources.proto cs3/sharing/collaboration/v1beta1/collaboration_api.proto cs3/sharing/collaboration/v1beta1/resources.proto cs3/sharing/link/v1beta1/link_api.proto cs3/sharing/link/v1beta1/resources.proto cs3/sharing/ocm/v1beta1/ocm_api.proto cs3/sharing/ocm/v1beta1/resources.proto cs3/storage/provider/v1beta1/provider_api.proto cs3/storage/provider/v1beta1/resources.proto cs3/storage/registry/v1beta1/registry_api.proto cs3/storage/registry/v1beta1/resources.proto --proto_path . --proto_path ./third_party
```

**Pull request merged**
