### PR TITLE
Prevent pushing to master when target repo def. branch is main

### PR DESCRIPTION
**Pull request by SamuAlfageme**
...until all the default branches have been moved to use 'main'

### CODE REVIEW

**Review by ishank011 — COMMENTED** [review]
Just change it to `protoBranch := getGitBranch(repo)`?

**Comment by ishank011** [comment]
Okay no but add a check that it only runs from master
```
if getGitBranch(".") != "master" {
    return
}
```

**Comment by SamuAlfageme** [comment]
@ishank011 thought about it, but it'd modify the current logic... it won't make a difference on the current CI pipelines ([scoped to master](https://github.com/cs3org/cs3apis/blob/master/.drone.yml#L12)) but maybe this image was intended to be able to sync cs3apis branches in the bindings repos as well... cc/ @labkode

**Comment by ishank011** [comment]
Ah okay but do we really need those? Looking at https://github.com/cs3org/python-cs3apis/branches/, the latest one is 7 months old. How did those get triggered? Maybe the CI config changed?

**Comment by ishank011** [comment]
Anyway, I'd still vote for restricting push access to master only

**Comment by SamuAlfageme** [comment]
@ishank011 found a run of the `build-and-publish` job for a branch diff. than master in here: https://cloud.drone.io/cs3org/cs3apis/109/1/2. 

It indeed seems like there was a diff. PR workflow before: https://github.com/cs3org/cs3apis/commit/c41553d922217f586d6d5a99c2c2b6fd10fd3140

**Comment by labkode** [comment]
Should we rename the branch to main and change accordingly rather than maintaining a workaround?

**Comment by SamuAlfageme** [comment]
@labkode done:
- [x] upstream/master  -> upstream/main in `cs3apis`
- [x] upstream/master  -> upstream/main in `python-cs3apis`
- [x] upstream/master  -> upstream/main in `js-cs3apis`
- [x] upstream/master  -> upstream/main in `go-cs3apis`
- [x] https://github.com/cs3org/cs3apis/commit/c2d1034e7c0a36523bb412d77f47e388e4538f42 
- [x] https://github.com/cs3org/python-cs3apis/commit/bbc39c15d752342109a7fe50da2d7b7fc13db7da
- [x] https://github.com/cs3org/js-cs3apis/commit/e05814f06fb68eb41f380a660242e356f5dc4ada

**Pull request closed without merging**
